name: destroy resources
on: 
    workflow_dispatch:

env:
    TF_VAR_region: us-west-2
    TF_VERSION: 1.5.7
jobs:
    destroy:
        runs-on: ubuntu-latest
        steps: 
           - name: checkout repo
             uses: actions/checkout@v2

           - name: configure aws credentials
             uses: aws-actions/configure-aws-credentials@v3
             with: 
               aws-access-key-id: ${{ secrets.AWS_ACESS_KEY }}
               aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
               aws-region: ${{ env.TF_VAR_region}}

           - name: Set up terraform
             uses: hashicorp/setup-terraform@v1
             with:
               terraform_version: 1.5.7
            
           - name: terraform init
             run: terraform init
        
           - name: terraform plan
             run: terraform plan -destroy -out=tfplan

           - name: terraform apply
             run: terraform apply -auto-approve tfplan