name: destroy resources
on: 
    push:
        branches:
            - main
jobs:
    destroy:
        runs-on: ubuntu-latest
        steps: 
           - name: checkout repo
             uses: actions/checkout@v2

           - name: Set up terraform
             uses: hashicorp/setup-terraform@v1
             with:
               terraform_version: 1.5.7
            
           - name: terraform init
             run: terraform init
        
           - name: terraform plan
             run: terraform plan -destroy -out=tfplan

           - name: terraform apply
             run: terraform apply -auto-approve tfplan